package com.bridgelabz.oopsbannerapp;

/**
* 00PSBannerApp UC2 - 00PS Banner Display Application
*
* This class demonstrates the creation of a visual banner displaying the word "00PS"
* using ASCII art composed of asterisks (*) and spaces. The banner is printed to the
* console using individual print statements for each line, creating a decorative
* text effect.
* 
* The banner is generated by printing predefined string patterns line by line,
* where each line contributes to forming the letters 0, 0, P, and S in a stylized format.
* This extends a basic user story by adding visual presentation to a simple message output.
* 
* @author Thamarai Kannan
* @version 2.0
*/

public class OOPSBannerApp {

	public static void main(String[] args) {
		
		System.out.println("   ***   " + " " + "   ***   " + " " + "******   " + "   ***** ");
		System.out.println(" **   ** " + " " + " **   ** " + " " + "**    ** " + " **      ");
		System.out.println("**     **" + " " + "**     **" + " " + "**    ** " + "**       ");
		System.out.println("**     **" + " " + "**     **" + " " + "******   " + "  *****  ");
		System.out.println("**     **" + " " + "**     **" + " " + "**       " + "      ** ");
		System.out.println(" **   ** " + " " + " **   ** " + " " + "**       " + " **   ** ");
		System.out.println("   ***   " + " " + "   ***   " + " " + "**       " + "  *****  ");
	}

}
